---
title: "Comment utiliser ce repository"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Rappel pour ce cours

  * Notation : 20 % Quizz, 20 % participation, 60 % examen final (TP)
  * Pour les questions, par email (cf l'email envoyé au groupe en fin de cours)
  

## Accéder et importer les fichiers

Plusieurs options sont possibles :

  * importer seulement les fichiers qui vous intéresse, pour cela cliquez sur ceux-ci puis vous pourrez les télécharger
  
  * si vous avez un compte sur Github (je vous le conseille, c'est gratuit et les étudiants ont accès à la fonctionnalité repository privé)
  
    + cloner le repository en entier : par ce moyen vous importez l'ensemble des fichiers et des branches
  
    + forker le projet sur votre espace Github


## Où chercher les informations et les scripts

### Jour 1 (scripts non complets)

* Préparation du Quizz

  + `ar1` (activité rapide 1, utiliser le `.html` pour le lire et le `.Rmd` pour voir le script du rapport R markdown) contient les informations relatives aux exercices de début de cours
  
  + à venir : transcript des exercices

* TP (et préparation de l'examen final)

  + `lm.R` est le script pour le modèle linéaire pour l'exercice 1 du TP
  + `decat_pca` est le rapport de l'excercice 2
  + l'exercice 3 avec le script excel pour la PCA

### Jour 2

  + `ar2`
  + `retour_blended`
  + `TP2_lm`